### ISSUE TITLE
Capitao is spelled wrongly in the SQLite database

### ISSUE THREAD

**Issue by chuahou** [captainturtle/r6siegetracker#1]
This doesn't break anything, but could cause potential minor headaches. In the SQLite database, Capitao is spelled as `capiato`. In the table `op_stats`,  Capitao stats are under the columns `capiato_tp`, `capiato_rw` etc.

**Comment by captainturtle** [comment]
Great catch. The origin of the typo is located at constants.py:
https://github.com/captainturtle/r6siegetracker/blob/master/r6siegetracker/constants.py#L28
I will be making an update.

**Comment by captainturtle** [comment]
Pushed a fix!
